### Hello World

In [1]:
print('Hello World')

Hello World


### Array Operations

In [4]:
import numpy as np

In [5]:
num = np.array([56,12,34,87,19,52,63,27])


In [6]:
print(num)


[56 12 34 87 19 52 63 27]


In [7]:
num

array([56, 12, 34, 87, 19, 52, 63, 27])

In [8]:
num[3]

87

In [9]:
num[3]= 64
num

array([56, 12, 34, 64, 19, 52, 63, 27])

In [10]:
num[-2]


63

In [11]:
num[2:6]


array([34, 64, 19, 52])

In [12]:
num.dtype

dtype('int32')

In [13]:
num.size


8

In [14]:
num.shape

(8,)

In [15]:
num = np.array([56,12,34,87,19.23,52,63,27])

In [16]:
num

array([56.  , 12.  , 34.  , 87.  , 19.23, 52.  , 63.  , 27.  ])

In [17]:
num[1]


12.0

In [18]:
num.dtype

dtype('float64')

In [19]:
num = np.array([56,12,34,87,19,'hello',52,63,27])

In [20]:
num

array(['56', '12', '34', '87', '19', 'hello', '52', '63', '27'],
      dtype='<U11')

In [21]:
ord('a')

97

In [22]:
ord('A')

65

In [23]:
chr(69)

'E'

In [29]:
city = np.array(['पुणे', ' मुंबई ', ' नागपूर', '  नाशिक '])

In [25]:
city[3]

'  नाशिक '

In [26]:
city[0]*10

'पुणेपुणेपुणेपुणेपुणेपुणेपुणेपुणेपुणेपुणे'

In [27]:
city[0].startswith('पु')

True

In [30]:
city


array(['पुणे', ' मुंबई ', ' नागपूर', '  नाशिक '], dtype='<U8')

In [31]:
num = np.array([56,12,34,87,19,52,63,27])
x = ([56,12,34,87,19,52,63,27])

In [32]:
x * 2

[56, 12, 34, 87, 19, 52, 63, 27, 56, 12, 34, 87, 19, 52, 63, 27]

In [33]:
num * 2

array([112,  24,  68, 174,  38, 104, 126,  54])

In [36]:
num - 10

array([46,  2, 24, 77,  9, 42, 53, 17])

In [35]:
num / 10

array([5.6, 1.2, 3.4, 8.7, 1.9, 5.2, 6.3, 2.7])

In [37]:
num > 40

array([ True, False, False,  True, False,  True,  True, False])

In [38]:
52 in num

True

In [39]:
57 not in num

True

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.empty(6)

array([ 1.54433083e-307, -3.30674726e-240,  1.12646967e-321,
        9.03293654e+271,  4.98131536e+151,  1.54761488e+262])

In [44]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [46]:
list(range(2,15,3))

[2, 5, 8, 11, 14]

In [47]:
list(range(20,2,-2))

[20, 18, 16, 14, 12, 10, 8, 6, 4]

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [51]:
np.arange(20,5,-2)

array([20, 18, 16, 14, 12, 10,  8,  6])

In [52]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [53]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [54]:
num.max()

87

In [55]:
num.mean()

43.75

In [56]:
num.argmax()

3

In [57]:
num.sort()

In [58]:
num

array([12, 19, 27, 34, 52, 56, 63, 87])

In [59]:
np.linspace(1,10,12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [60]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Two Dimensional Array

In [61]:
x = np.array([[1,3,6,5],[6,9,8,0],[2,1,4,3]])

In [62]:
x

array([[1, 3, 6, 5],
       [6, 9, 8, 0],
       [2, 1, 4, 3]])

In [63]:
### Matrix is collection of vectors of equal length

In [64]:
x.shape

(3, 4)

In [65]:
x.size

12

In [66]:
x[1][2]

8

In [67]:
x.reshape(4,3)

array([[1, 3, 6],
       [5, 6, 9],
       [8, 0, 2],
       [1, 4, 3]])

In [68]:
x.reshape(6,2)

array([[1, 3],
       [6, 5],
       [6, 9],
       [8, 0],
       [2, 1],
       [4, 3]])

In [69]:
x.reshape(-1,2)

array([[1, 3],
       [6, 5],
       [6, 9],
       [8, 0],
       [2, 1],
       [4, 3]])

In [70]:
x.reshape(4,-1)

array([[1, 3, 6],
       [5, 6, 9],
       [8, 0, 2],
       [1, 4, 3]])

In [71]:
x.flatten()

array([1, 3, 6, 5, 6, 9, 8, 0, 2, 1, 4, 3])